version: "3"

services:
  app:
    container_name: "pywebio-docker"
    restart: always
    build: app
    networks:
      - default_network
    ports:
      - "${PORTS}:8080"
    environment:
      - TEST_VAR = ${TEST_VAR}
    env_file: stack.env

networks:
  default_network:
    external: true