version: "3"

services:
  app:
    container_name: "pywebio-docker"
    restart: always
    build: app
    networks:
      - nginxproxymanager_default
    ports:
      - 8080:8080
    environment:
      - TEST_VAR = ${TEST_VAR}

networks:
  nginxproxymanager_default:
    external: true